/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author family
 */
public class GUINomina extends javax.swing.JFrame {
    
    private Nomina nomina;

    /**
     * Creates new form GUINomina
     */
    public GUINomina() {
        initComponents();
        nomina = new Nomina();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(9, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nómina");
        jPanel1.add(jLabel1);

        jButton8.setText("Calcular sueldo bruto");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton1.setText("Calcular sueldo real");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Sueldos reales de empleados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Suma de sueldos reales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Promedio de sueldos reales");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Cedulas de los empleados");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("Total a pagar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("Empleado que gana menos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        double suma = nomina.calcularTotalAPagar(emps);
        JOptionPane.showMessageDialog(null, "El total a pagar por parte de la empresa es: "+suma);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado?");
        double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado?"));
        Empleado emp = new Empleado(cedula, sueldoBruto);
        double sueldoBrutoEmp = nomina.calcularSueldoReal(emp);
        JOptionPane.showMessageDialog(null, "El sueldo real del empleado es: "+sueldoBrutoEmp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado?");
        double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado?"));
        Empleado emp = new Empleado(cedula, sueldoBruto);
        double sueldoBrutoEmp = nomina.calcularSueldoBruto(emp);
        JOptionPane.showMessageDialog(null, "El sueldo en bruto del empleado es: "+sueldoBrutoEmp);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        
        double[] sueldosReales = nomina.calcularSueldosEmpleados(emps);
        String resp = "";
        for (int i = 0; i<sueldosReales.length ; i++){
            resp += "\n"+sueldosReales[i];
        }
        JOptionPane.showMessageDialog(null, "El sueldo real de los empleados que ingresó es: "+resp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        double suma = nomina.calcularSumaSueldos(emps);
        JOptionPane.showMessageDialog(null, "La suma de los sueldos reales de los empleados que ingresó es: "+suma);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        double suma = nomina.calcularPromedioSueldos(emps);
        JOptionPane.showMessageDialog(null, "El promedio de los sueldos reales de los empleados que ingresó es: "+suma);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        ArrayList <String> ceds = nomina.obtenerIdEmpleados(emps);
        String resp = "";
        for (String ced : ceds) {
            resp += "\n" + ced;
        }
        JOptionPane.showMessageDialog(null, "Las cédulas de los empleados que ingresó son: "+resp);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int num = Integer.parseInt(JOptionPane.showInputDialog(null, "¿Cuántos empleados desea ingresar?"));
        Empleado[] emps = new Empleado[num];
        for (int i = 0;i < num; i++){
            String cedula = JOptionPane.showInputDialog(null, "¿Cuál es la cedula del empleado " +(i+1)+"?");
            double sueldoBruto = Double.parseDouble(JOptionPane.showInputDialog(null, "¿Cuál es el sueldo en bruto del empleado " +(i+1)+"?"));
            Empleado emp = new Empleado(cedula, sueldoBruto);
            emps[i] = emp;
        }
        Empleado emp = nomina.empleadoGanaMenos(emps);
        JOptionPane.showMessageDialog(null, "El empleado que gana menos es el de la cedula: "+emp.getIdEmpleado());
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
